services:
  azula:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENV=development
    container_name: azula-bot
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    restart: unless-stopped
