version: "3.8"

services:
  azula:
    build:
      args:
        NODE_ENV: production
    env_file:
      - .env
      - .env.production
    image: ${DOCKER_REGISTRY}azula:latest
    restart: unless-stopped
