services:
  azula:
    build:
      context: ./
    env_file:
      - .env
      - .env.production
    image: ${DOCKER_REGISTRY}azula:latest
    restart: unless-stopped
    configs:
      - source: azula_cookies_v1
        target: /usr/src/app/persistent/cookies.txt

configs:
  azula_cookies_v1:
    external: true
